// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm5_2xKLc7sHLXXtmxCaeqA9tZuGtWlVg',
    appId: '1:253795056850:web:916bd272669aae479dc10b',
    messagingSenderId: '253795056850',
    projectId: 'sign-detector-90027',
    authDomain: 'sign-detector-90027.firebaseapp.com',
    storageBucket: 'sign-detector-90027.appspot.com',
    measurementId: 'G-ZMTKW5D6GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKRn5HpoDhFGdGIiP_mj0LHvbV7qyE6WY',
    appId: '1:253795056850:android:9c194d35d332aa619dc10b',
    messagingSenderId: '253795056850',
    projectId: 'sign-detector-90027',
    storageBucket: 'sign-detector-90027.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmZ3241PRuMpCvbKMohjve_6CINnjUCig',
    appId: '1:253795056850:ios:42de360bb733a7d19dc10b',
    messagingSenderId: '253795056850',
    projectId: 'sign-detector-90027',
    storageBucket: 'sign-detector-90027.appspot.com',
    iosBundleId: 'com.example.signDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmZ3241PRuMpCvbKMohjve_6CINnjUCig',
    appId: '1:253795056850:ios:42de360bb733a7d19dc10b',
    messagingSenderId: '253795056850',
    projectId: 'sign-detector-90027',
    storageBucket: 'sign-detector-90027.appspot.com',
    iosBundleId: 'com.example.signDetector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm5_2xKLc7sHLXXtmxCaeqA9tZuGtWlVg',
    appId: '1:253795056850:web:c1bbaa20f9f2b3759dc10b',
    messagingSenderId: '253795056850',
    projectId: 'sign-detector-90027',
    authDomain: 'sign-detector-90027.firebaseapp.com',
    storageBucket: 'sign-detector-90027.appspot.com',
    measurementId: 'G-12LLPG7YY4',
  );
}
